version: '3'

services:
  app:
    build: .
    image: spring-boot-img
    ports:
      - 8080:8080
    networks:
      - simple-app-pg
    depends_on:
      - pgdb
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://pgdb:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  pgdb:
    image: 'postgres'
#    ports:
#      - "5432:5432"
    networks:
      - simple-app-pg
    container_name: pgdb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

networks:
  simple-app-pg: